### ISSUE TITLE
Starlite Piccolo ORM template

### ISSUE THREAD

**Issue by sinisaos** [v3ss0n/awesome-starlite#2]
Hi, if you want and think it's good enough, you can add the [Starlite Piccolo](https://github.com/sinisaos/starlite-piccolo) starter template to your list. The template includes several useful things like user authentication, user management (with user profile and crud dashboard), admin UI, etc. Thanks.

**Comment by v3ss0n** [comment]
Thanks , thats cool! , i am looking into trying picolo too .  I had also create a cookiecutter , would be nice to have a starlite picollo cookiecutter. You could check this out : https://github.com/v3ss0n/starlite-halfstack-cookiecutter

**Comment by v3ss0n** [comment]
added.

**Comment by sinisaos** [comment]
Great. Thanks.
